language: python
cache: pip
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

install:
  - pip install tox-travis coverage coveralls

script:
  - tox

after_success:
  - coverage report -m
  - coveralls
