language: python
matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: xenial
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - pip install tox tox-travis coverage coveralls

script:
  - tox

after_success:
  - coverage report -m
  - coveralls
